server:
  port: 8086

el-aparato:
  keycloak:
    serverUrl: http://localhost:8080
    realm: el-aparato
    clientId: api-internal-users-client
    clientSecret: "**********"

spring:
  application:
    name: elaparato
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/el-aparato
  datasource:
    url: jdbc:mysql://localhost:3306/elaparato?createDatabaseIfNotExist=true
    username: root
    password: asease22
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    org.springframework.security: TRACE
